# Generated by Django 3.2.9 on 2021-12-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcepost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resourcepost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resourcepost',
            name='day',
        ),
        migrations.RemoveField(
            model_name='resourcepost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='resourcepost',
            name='month',
        ),
        migrations.RemoveField(
            model_name='resourcepost',
            name='slug',
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
