# Generated by Django 3.2.9 on 2021-12-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_start', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
